# Generated by Django 6.1.1 on 2026-09-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
